# use Ganache's forked mainnet mode as the default network
# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: ftm-main-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# require OpenZepplin Contracts
dependencies:
  - storming0x/yearn-vaults@0.4.3-sol8
  - OpenZeppelin/openzeppelin-contracts@4.4.1
  - 16slim/v3-core@1.0.2-solc-0.8-simulate

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.12
    remappings:
      - "@yearnvaults=storming0x/yearn-vaults@0.4.3-sol8"
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.4.1"
      - "@uniswap=16slim/v3-core@1.0.2-solc-0.8-simulate"

reports:
  exclude_contracts:
    - SafeMath
